### PR TITLE
Conflicts: Fix symbol conflicts between other libraries

### PR DESCRIPTION
**Pull request by 1480c1**
Fixed conflicts between SVT-VP9 and current SVT-AV1 master, libvpx master, and SVT-HEVC master.

### CODE REVIEW

**Comment by tianjunwork** [comment]
To build both static svt-vp9 and libvpx in ffmpeg:
` ./configure --enable-libsvtvp9 --enable-libvpx --enable-static --disable-shared`

**Comment by 1480c1** [comment]
Some of the files in App/ use some of the symbols from the library that have been renamed like `eb_strnlen_ss` was renamed to `eb_vp9_strnlen_ss` and `PictureManagerKernel` was renamed to `eb_vp9_PictureManagerKernel` so to match those changes, they have been changed in the app folder too. The one in `Source/App/EbAppProcessCmd.c` isn't necessary since it's just a warning about the symbol rather than calling it

**Comment by intelmark** [comment]
Just confirming that the PR involves function name changes only.  Assuming there are no changes to any of the make/build files, and no documentation changes would be required.

Awesome job on this.  Great to make this change while activity in the repo is minimal.

**Comment by tianjunwork** [comment]
Thanks Mark verifying the PR.

**Pull request merged**
