### PR TITLE
Add missing default interface values

### PR DESCRIPTION
**Pull request by tianjunwork**
Signed-off-by: Jun Tian <jun.tian@intel.com>

### CODE REVIEW

**Comment by intelmark** [comment]
Looks fine.  Wonder why it was commented out in the first place.

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-VP9/blob/7951c3cf6773c5e0ede00e4ce3e3ad2f7e090cfb/Source/App/EbAppConfig.c#L348

seems maybe it's due to this line?

**Comment by tianjunwork** [comment]
@intelmark , the code is copied over from SVT-HEVC. During that time, there is no effort to add those features. So the lines are commented out. They are in the initial commit.

**Comment by tianjunwork** [comment]
@1480c1 yeah, they are set in sample app. But not for other apps using the lib directly.

**Review by intelmark — APPROVED** [review]

**Pull request merged**
