### PR TITLE
[Do not merge]ffmpeg-master: Worked around the "Too many invisible frames" issue for mkv/webm/mp4/dash

### PR DESCRIPTION
**Pull request by guojiansheng0925**

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925 Thank you making this patch. To let CI pass, you can run them on ffmpeg master by modifying the CI script in this PR.
1, revert this change. https://github.com/OpenVisualCloud/SVT-VP9/pull/87
2, make same change as Austin did in travis.yml. https://github.com/OpenVisualCloud/SVT-VP9/pull/83/files#diff-354f30a63fb0907d4ad57269548329e3

**Comment by guojiansheng0925** [comment]
hi, @tianjunwork, I have revised travis.yml but the CI failed. I also tried to revert #87 and commit again and I have make sure the patch file works in my local environment. Could you please help to check why the CI failed?

**Comment by 1480c1** [comment]
For linux:
```bash
libavformat/movenc.c: In function ‘handle_eac3’:
libavformat/movenc.c:522:9: warning: ‘av_copy_packet_side_data’ is deprecated [-Wdeprecated-declarations]
         if ((ret = av_copy_packet_side_data(&info->pkt, pkt)) < 0)
         ^~
In file included from libavformat/avformat.h:317:0,
                 from libavformat/movenc.h:27,
                 from libavformat/movenc.c:27:
./libavcodec/avcodec.h:4532:5: note: declared here
 int av_copy_packet_side_data(AVPacket *dst, const AVPacket *src);
     ^~~~~~~~~~~~~~~~~~~~~~~~
libavformat/movenc.c: In function ‘mov_check_bitstream’:
libavformat/movenc.c:6957:10: error: ‘avpkt’ undeclared (first use in this function); did you mean ‘pkt’?
     if ((avpkt->flags & AV_PKT_FLAG_SVT_VP9_EXT_ON) ||
          ^~~~~
          pkt
libavformat/movenc.c:6957:10: note: each undeclared identifier is reported only once for each function it appears in
ffbuild/common.mak:59: recipe for target 'libavformat/movenc.o' failed
```

For windows, it seems it's because we are pulling the 4.2 branch of ffmpeg, you would need to change the link in the appveyor.yml file from `https://github.com/FFmpeg/FFmpeg/archive/release/4.2.zip` to `https://github.com/FFmpeg/FFmpeg/archive/master.zip` to download the master branch

**Comment by guojiansheng0925** [comment]
@1480c1 Thank you very much.

**Comment by 1480c1** [comment]
@guojiansheng0925, I would recommend you to do your commits on a separate branch next time
```bash
git branch -b <branch name>
git add ...
git commit ...
git push --set-upstream origin <branch name>
```
that way, you can have multiple branches etc on your fork and you can easily sync your master branch by either
```bash
git remote add upstream https://github.com/OpenVisualCloud/SVT-VP9.git
git fetch --all -pf
git pull upstream master
```
or
```bash
git pull https://github.com/OpenVisualCloud/SVT-VP9.git master:master
```

**Comment by intelmark** [comment]
@Austin-Hu  thanks for this contribution!

**Comment by 1480c1** [comment]
@guojiansheng0925 can you check to make sure if your patches still apply onto ffmpeg's master branch?
```none
error: patch failed: configure:6336
error: configure: patch does not apply
error: patch failed: libavcodec/avcodec.h:1549
error: libavcodec/avcodec.h: patch does not apply
error: patch failed: libavformat/matroskaenc.c:159
error: libavformat/matroskaenc.c: patch does not apply
```

**Comment by guojiansheng0925** [comment]
Hi, @1480c1  I have update the 0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch.
And I will update 0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch later.

**Comment by 1480c1** [comment]
> patch

Thank you

**Comment by 1480c1** [comment]
@guojiansheng0925 you seem to be missing changes in the `libavcodec/Makefile`

```none
OBJS-$(CONFIG_LIBSVT_VP9_ENCODER)         += libsvt_vp9.o
```

**Comment by 1480c1** [comment]
https://gist.github.com/1480c1/ecc1dd3a15093398492c86f2314f4a67#file-0001-add-ability-for-ffmpeg-to-run-svt-vp9-patch

Here's a version of the patch with the missing files applied in

**Comment by 1480c1** [comment]
@tianjunwork @guojiansheng0925 would it be possible to merge these patches as separate files from the main ones in the main repo? Something like `ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch` and `ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch`. That way they aren't stuck in a PR and it would be easier to manage and maintain

**Comment by guojiansheng0925** [comment]
Hi @tianjunwork  @1480c1 , 
I am sorry for the previous patch, I only focused on the conflict files and forgot to add other files.
I have update it.

**Comment by guojiansheng0925** [comment]
> @tianjunwork @guojiansheng0925 would it be possible to merge these patches as separate files from the main ones in the main repo? Something like `ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch` and `ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch`. That way they aren't stuck in a PR and it would be easier to manage and maintain

Good idea. Do you think so? @tianjunwork

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925 , sure, we can merge these. Please also document the usage in case confusion.

**Pull request closed without merging**
