### PR TITLE
FFmpeg: make master patch compatible with master

### PR DESCRIPTION
**Pull request by Geo25rey**

### CODE REVIEW

**Comment by tianjunwork** [comment]
Thank you @Geo25rey for the patch.
Is the change of `libwavpack` in ffmpeg master causing the issue? If yes, maybe putting `libsvtvp9` in front of `libvpx`? If it works, we can avoid adding another patch file.

**Comment by 1480c1** [comment]
@tianjunwork @guojiansheng0925 I am wondering if it would be better to split the patch files into two separate patches, one being a patch file to add the configure, makefile, and other file changes that usually changes based on ffmpeg version, and another second patch that only contains libsvt_vp9.c. That way, we can make sure that any change to libsvt_vp9.c will be applied to all ffmpeg version without needing to regenerate the other patches, and the individual ffmpeg version-specific changes can be made quickly while also making sure we can customize the patches to whichever version we need to?

**Comment by 1480c1** [comment]
That way instead of
```none
diff --git a/libavcodec/libsvt_vp9.c b/libavcodec/libsvt_vp9.c
new file mode 100644
index 0000000000..a557019c9b
--- /dev/null
+++ b/libavcodec/libsvt_vp9.c
```
being repeated in each patch file, it's moved to it's own commit and patch?

**Comment by Geo25rey** [comment]
It seems that in addition to the removal of `libwavpack`, the most line numbers have changed. Also, it's probably a good idea to keep a specific patch for the master branch for packages that rely on `ffmpeg/master` like [ffmpeg-amd-full](https://aur.archlinux.org/packages/ffmpeg-amd-full-git). My guess is this patch will become version n4.4 of ffmpeg.

**Comment by 1480c1** [comment]
I think it may be fine for us to deviate a bit in the patchset since it seems they use their own patch version as well (https://aur.archlinux.org/cgit/aur.git/tree/040-ffmpeg-add-svt-vp9.patch?h=ffmpeg-amd-full-git), but also I think the benefit in terms of maintenance will be much larger than what we currently have to do with multiple patches containing the same file, and thus whenever we need to update one, we have to update them all.

**Comment by tianjunwork** [comment]
@1480c1 Chris, https://github.com/OpenVisualCloud/SVT-VP9/issues/108, libsvt_vp9.c may also have conflict but with less chance. Split the patch files may not reduce much maintenance effort. Also it may confuse the user.

**Comment by Geo25rey** [comment]
@tianjunwork So what's the status of this PR? What are my recommendations?

**Review by 1480c1 — APPROVED** [review]
Personally, patch seems fine as is since it fixes the issue that it sets out, it just feels like it will become annoying with the amount of patches we will accumulate

**Comment by tianjunwork** [comment]
Thanks Chris @1480c1 reviewing.
@Geo25rey Thank you for the contribution. I will test it one more time. Then go ahead with merge if no issue.

**Comment by Geo25rey** [comment]
Thanks @1480c1 and @tianjunwork. Glad to contribute.

**Review by tianjunwork — APPROVED** [review]

**Pull request merged**
