### PR TITLE
Add AppVeyor CI/CD

### PR DESCRIPTION
**Pull request by EwoutH**
This PR adds continuous integration & delivery with AppVeyor. SVT-VP9 gets build with Microsoft Visual Studio 2017 and Yasm 1.3.0. AppVeyor publishes `SvtVp9Enc.dll`, `SvtVp9Enc.exp`, `SvtVp9Enc.lib` and `SvtVp9EncApp.exe` in the Artifacts tab ([example](https://ci.appveyor.com/project/EwoutH/svt-vp9/build/artifacts)).

AppVeyor needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/appveyor) or on [ci.AppVeyor.com](https://ci.appveyor.com/project/OpenVisualCloud/SVT-VP9).

When enabled, AppVeyor publishes the artifacts with each build. When tagging a new (pre)release, AppVeyor will also upload these files to GitHub, creating a release page.

To enable uploading to GitHub Releases, a maintainer needs to update this patch with his personal authentication token. You can generate one on https://github.com/settings/tokens/new (select `public_repo` as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 21 (after `secure:`) in the `appveyor.yml` file.

### CODE REVIEW

**Comment by EwoutH** [comment]
@hassount

**Comment by hassount** [comment]
@EwoutH 
this should be ready to merge after fixing the conflict ?

**Comment by EwoutH** [comment]
@hassount Should be good to go!

**Comment by EwoutH** [comment]
@hassount Thanks for merging! Don't forget to enable [AppVeyor](https://ci.appveyor.com/project/OpenVisualCloud/SVT-VP9) and [Travis](https://travis-ci.com/OpenVisualCloud/SVT-VP9)!

**Comment by EwoutH** [comment]
@hassount AppVeyor still needs to be enabled!

**Comment by hassount** [comment]
@EwoutH I see it enabled in the repo settings, is there any where else I would need to link it? 
git

**Comment by EwoutH** [comment]
@hassount AppVeyor should become publicly visible here: https://ci.appveyor.com/project/OpenVisualCloud/SVT-VP9

If you sign in on AppVeyor, does SVT-VP9 appear here? https://ci.appveyor.com/projects

**Pull request merged**
